import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
})

const thunder_hc = localFont({
	src: "../public/fonts/Thunder-BoldHC.otf",
	weight: "700",
	variable: "--font-thunder_hc",
	display: "swap",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${thunder_hc.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	)
}
